### ISSUE TITLE
[Guides] Add a .net page

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#189]
First step: find a volunteer in our .net channel to give us some good tutorials, first steps, blogs etc.

**Comment by CryptoJones** [comment]
I got it.

**Comment by jjhampton** [comment]
I noticed that #119 is about adding an Android page, and similarlyl, this issue is about adding a .NET page.  

In addition to those two, there are other platforms that people would like to develop sub-pages for (front-end web, back-end web, mobile, data science, game development, VR software, who knows what else).

I propose that we develop a list of ALL the main software development areas that should have individual pages.  For each page, we would display content devoted helping Vets learn to develop for that platform (schools, online training resources, tutorials, etc).

**Comment by davidmolina** [comment]
Good suggestion. Let's do that.

**Comment by rickr** [comment]
FWIW I am tracking these efforts in a milestone: 
https://github.com/OperationCode/operationcode/milestones/Getting%20Started

It has a bit more info on what each of these pages should have.

**Comment by davidmolina** [comment]
Perfect. Thanks Rick.

**Comment by davidmolina** [comment]
This [commit](https://github.com/OperationCode/operationcode/commit/754fd004e99a99f908d5b89df6463174f50e0f02) fixes this.
