### ISSUE TITLE
Signup email sent with wrong subject and minor typos in body

### ISSUE THREAD

**Issue by wcriss44** [OperationCode/operationcode#598]
As a visitor,
When I signed up for Operation Code, using the website, I received a two emails. One email inviting me to Slack and the other welcoming me to Operation Code.

The email for Operation Code was sent with the following subject: "Reset password instructions"

It should have a subject that welcomes me to the site.

Additional Information (eg browser version, screenshots etc):

The content of the email is correct and as expected -- it welcomes me to the site. I did notice two typo sections in the email. I've included the section containing them below. If you would like I can open a new issue for these. My assumption is that they can be fixed while fixing the email subject.

## excerpt from email:
Hi all. My name is David Molina, ex-Army Captain and interested in webdev, ruby, rails. I'm originally from Washington State currently living in Portland.

## should read:
Hi all. My name is David Molina, I am an ex-Army Captain and I am interested in webdev, ruby, rails. I'm originally from Washington State but currently live in Portland.

## excerpt from email:
The Operation Code website uses Ruby On Rails. If you want to dive in and help you can get started by reading our docs, or asking around in the #operationcode-dot-org slack channel.

## should read:
The Operation Code website uses Ruby On Rails. If you want to dive in and help you can get started by reading our docs or asking around in the #operationcode-dot-org slack channel.

## note:
The change to the one above was minor. The comma after docs, which is a link in the email, should be removed.

**Comment by DanielKim1** [comment]
Haven't contributed to Operation Code before, but I think I can fix this. I'll start working on this issue

**Comment by sfillm07** [comment]
I will make an attempt to work on this issue, first time

**Comment by rickr** [comment]
All yours! Please let me know if you have any questions.

**Comment by sfillm07** [comment]
Someone already completed this...The subject line in the user_mailer.rb has already been changed and the grammatical errors in the welcome.html.ert are all taken care of.

**Comment by rickr** [comment]
That's not the correct location. This is a remnant of the profile system we had that didn't see a lot of traction. See the [registrations controller](https://github.com/OperationCode/operationcode/blob/master/app/controllers/veterans/registrations_controller.rb#L27) which is calling a (devise)[http://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Recoverable/ClassMethods) method). That template actually called is located [here](https://github.com/OperationCode/operationcode/blob/master/app/views/devise/mailer/reset_password_instructions.html.erb).

Since I don't think we'll be going back to using profiles in the near term I'd be OK with either going back to the welcome mailer or updating the existing system to work. 

This [SO post](http://stackoverflow.com/questions/14600229/how-to-change-devise-password-reset-instruction-emails-subject) should help with the latter.

**Comment by rickr** [comment]
Fixed in #612
