### ISSUE TITLE
Create page for mentor sign up

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#629]
As a mentor
When I attempt to sign up
It should display a form with a call to action of something other than 'Teach me to code'.

Maybe something like 'I want to mentor', or 'I want to help Operation Code'.

**Comment by C-Lion** [comment]
I'd like to be assigned this issue.

**Comment by rickr** [comment]
It's all yours

**Comment by roberttysor** [comment]
Is this closed? Have some flight time today and boredom.

**Comment by rickr** [comment]
It's not closed. Please let me know if you need more details.

**Comment by roberttysor** [comment]
Just landed in San Diego. I'll get some things together this evening and give you anything I get.

Thanks
Rob

Sent from my iPhone

On Apr 5, 2017, at 6:50 AM, Rick <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not closed. Please let me know if you need more details.

**Comment by C-Lion** [comment]
Go for it!

**Comment by sdoyle0** [comment]
I started to take a look at this last night and was hoping for a little insight/help. It looks like there are a couple options. Since there's already a Mentor model that extends a Veteran, it looks like it could be done passing a parameter to the existing veteran registration path, which I started down and can be seen [here](https://github.com/sdoyle0/operationcode/commit/d9ffd3c62596b40e5f48659eaa7fda9178ff8f94). If the two pages may diverge a lot, however, it may make more sense to go ahead and creator mentor view, controllers, etc. Any suggestions?

**Comment by fredosantana** [comment]
Agreed @sdoyle0. I'd assume that features for mentors would require separate views and controllers from veteran features. I can assist with this.

**Comment by sdoyle0** [comment]
I committed some initial steps in the mentor_629 branch of my repository. Feel free to take a look and see what you think. Definitely open to suggestions. [mentor_629 repo](https://github.com/sdoyle0/operationcode/tree/mentor_629)

**Comment by sdoyle0** [comment]
@rickr, would you be able to take a look at the branch and see if that's what you were thinking for this new page? Or would it be better just to submit it as a pull request?
[Here](https://github.com/sdoyle0/operationcode/commit/e6ab16860cbdf8c9ae6ce7a82022e8703bebc2ec) is a link to the page showing the additions as well.
