### ISSUE TITLE
Investigate using BigCommerce for our store page

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#631]
Continuing discussion from #267

**Comment by sethbergman** [comment]
Let me get ahold of BC today and see what I can do for an awesome non-profit like yours. 😆

**Comment by rickr** [comment]
Maybe I'm not understanding when you say we don't have to manage inventory. 

With Big Commerce we will need to design and print merchandise with another service. We'll then have to store that merchandise, track when we need to order more, and ship it manually. 

Is all that correct?

**Comment by sethbergman** [comment]
There is a service that integrates with Bigommerce that handles shipping automatically, and another one that enables you to design and customize the shirts, gear, swag etc. I can get the manufacturer to integrate with the bc APIs to automate the entire process. 

I know that this sounds like a lot of work, but it is what I used to do every day while working there.

**Comment by sethbergman** [comment]
Let's see about getting a list of pros and cons comparing the two. Then we'll be in a better position to make the right decision.

**Comment by rickr** [comment]
That does seem like a lot of work, complexity and overhead. 
What do these additional services cost?

**Comment by sethbergman** [comment]
[Printful BC API App](https://www.bigcommerce.com/apps/printful-dropship-t-shirts-posters-leggings-and-more-print-products/)

The store would cost $29.95 / month and the app for printing and dropshipping the shirts is a free service. 

Keep in mind that I haven't tried to get you a discount on the store price yet.

**Comment by sethbergman** [comment]
The only overhead would be to put your product list on your store. I've already got a nice clean design and the e-commerce features are the best in the industry. The possibilities are endless. What's the cost of teespring?

**Comment by rickr** [comment]
We're going to use Threadless for now. The cost is free they just take a cut per shirt. 

It looks like they offer other items (coffee cups, notebooks etc). What's BigCommerces story there?

**Comment by rickr** [comment]
We're going to use Threadless for now. The cost is free they just take a cut per shirt.

It looks like they offer other items (coffee cups, notebooks etc). What's BigCommerces story there?
How does Printful make money?

Also please keep in mind I have a $0 budget. Any amount of money per month is going to be too much.

**Comment by MackenzieH** [comment]
After some research, Printful just takes a flat rate per item. On their products site (https://www.printful.com/custom-products) they give a list of all of their products and at what cost to you. Then on your site, you pick the prices for the merchandise so you make money (Printful suggests a 30% profit margin). Every source I've found states it as a free-up-front/no-set-up-fee service, so this is a $0/month option. They also have discounts if you end up doing higher volume, so that's another perk. 

There are several helpful reviews, here are a couple:
http://theabundantartist.com/printful-review-possibly-the-easiest-way-to-sell-your-prints-online/

http://www.brandbuildsell.com/review-my-love-hate-relationship-with-the-printful/

**Comment by hollomancer** [comment]
What would it take to get this up and running?

**Comment by rickr** [comment]
Printful would be $0/month but we would still be paying for the Big Commerce store at 30/month correct?

**Comment by sethbergman** [comment]
Yes that's correct. I found another $0 option though with teechip. I made a private campaign and there is not payment gateway setup yet (PayPal). Check it out here:
https://teechip.com/operationcode
![gildan-50-50-hoodie-161616](https://cloud.githubusercontent.com/assets/8031689/23445997/45802b8c-fe05-11e6-9ddf-610eef6cf8a9.jpg)

**Comment by MackenzieH** [comment]
Let me begin by saying I'm NOT down voting teechip. Upon first glance, it seemed like a great $0 cost vehicle for the project. I just wanted to do some research to clarify what it is and how it works. 
**HOW IT WORKS**
1. you put your designs on teechip's products (upload an image/design & they print on their merch.)
2. you set price, quantity of products, goal of profits, and duration of campaign
3. create an URL which leads to the teechip campaign and share so people will see, buy your products and support your campaign
*a side note about #3 - teechip.com isn't actually searchable for a particular campaign (at least not that I've found) so it's less of an online store.. it makes it difficult for people to stumble across a good cause. They do have featured campaigns, but I'm not sure how those are picked. So unless the URL for a specific campaign is used, I'm not sure how people would find that particular design. Also TBD is whether one campaign can have multiple designs or if a new campaign is required for each design.

All the products are made and shipped AFTER the campaign ends and the time limit for a campaign is a whole month so of course some of the things you ordered will take a month to arrive(again it depends on how long the campaign last). This is kind of Gofundme.com where you give money for a cause, but with teechip the person gives you something in exchange. You aren't required to meet your goal in order for them to produce. Even if you sell 1, they'll make it.

That being said, A LOT of the reviews (which are overwhelmingly negative) are complaints of the merchandise taking significantly longer than estimated. Some reviews even report never getting anything, despite paying. Teechip also has an 'auto restart' feature on campaigns, which has apparently caused some bugs with knowing when to actually start production (because again, production begins when the campaign ends). So this is potentially problematic if your campaign never "ends" with this auto restart.

**PAYMENTS**
Customers can pay via PayPal or via credit card.

Payouts/profits are made to you via PayPal 5 days after the campaign ends. Again, I don't know how the auto restart feature impacts this, I haven't come across anything from the seller point of view saying it's caused any issues. 

**ADDITIONAL NOTES**
- Many of the reviews and comments are against teechip because of content infringement. There's almost an anti-teechip crusade because of this. It's not their fault because they simply print what people upload to be printed, and they have infringing clauses on their sites and upon uploading. 
- Their customer service (which along with CC fees and fraud protection costs 7% of the gross payout) is reviewed to be terrible with wait times of over two hours and extreme hassles in trying to get updated order statuses. 

I realize there are potential pitfalls with every system, I was surprised and a bit bummed when this one had such majority negative reviews. I'm still researching a possible alternative and hope to post within a couple days with something of substance. Positive reviews for this platform DO exist!! So don't write it off, but if it's the chosen platform, just be aware of some of the potential issues.

**Comment by MackenzieH** [comment]
Because I didn't want to negate a free (and therefore very viable option), I've found a potential alternative. You can create what they call a custom store and they have a social marketplace where people who aren't familiar with the project may happen to come across merchandise and in turn, become aware of the project. 

**Storenvy**. Everything on their site says it's free, they take percentages of sales as payment from their marketplace, but no up front costs. Storenvy also has integration with a merchandise printing & shipping platform called **Print Aura**. This is also free, and has no up front cost. They do have a per item cost as well as shipping is an additional cost to the consumer. 

Again, after researching, I've found $0 up front cost when using these two. Print Aura also has a broad range of products on which to print, so that was also a plus compared to other platforms I've seen. 

Storenvy's pricing is as follows:
- no monthly fees, no listing fees
- if a sale is made through their marketplace (aka social platform I thought is kind of like Etsy), they keep 10%
- if s sale is made from the custom store (which again, is free to open your own store) they don't take any portion

Print Aura's pricing is as follows:
- no minimums or subscription fees
- see this site https://printaura.com/pricing for their pricing of individual items (too many to show on here)

So to determine the prices of items available, you'd have to consider the 10% and the cost from Print Aura. It may end up being a bit more for an item from the consumer/supporter perspective, but reminding them it's about the cause may help.
