### ISSUE TITLE
Create  Deploy Subdomain

### ISSUE THREAD

**Issue by brettt** [OperationCode/operationcode#719]
As a VISITOR
When I VISIT DEPLOY
It should maybe BE A SUBDOMAIN instead of a standalone page so it won't get caught up in rails and would be easier to update, etc.  Just a thought to make life easier.  

Bret (and David)

**Comment by rickr** [comment]
This sounds good to me. Before we move forward we need to ID how the page will be hosted.
@Wimsy113 are you moving back to GH pages?

**Comment by Wimsy113** [comment]
Deploy's got it's own thing, you can delete this.

**Comment by Wimsy113** [comment]
Also, I was mostly trying to keep Deploy separate from Operation Code stuff, because I didn't want people to start mixing up the two. It was supposed to be it's own entity that feeds into Operation Code. If we're trying to turn it into something like say an apprenticeship opportunity, then I'd totally not have any problems with adding it as a sub domain, but the idea was for it to be it's own thing at the time.

**Comment by rickr** [comment]
What's the domain? Is it ready for oc.org to link to?

**Comment by Wimsy113** [comment]
yup it's here [http://deployopcode.io](Deploy)

**Comment by rickr** [comment]
Ok in that case - to close this ticket:

- [ ] Update the menu URL for deploy to point to http://deployopcode.io
- [ ] Search for any additional references to deploy and replace those links as well

**Comment by feosuna1** [comment]
I'd like to work on this. PR incoming.
